steps:
# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy the cloudresume infra
  args: ['deployment-manager', 'deployments', 'update', 'cloudresume', '--config', 'deployment-manager/cloudresume.yaml']