steps:
# Pylint check
- name: 'python:3'
  id: Check the python package
  entrypoint: 'bash'
  args:
    - '-c'
    - |-
      pip install pylint
      pip install -r scripts/visitor_count/requirements.txt
      pylint scripts/

# Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Push the cloud function code to a bucket
  entrypoint: 'bash'
  args:
    - '-c'
    - |-
      apt install -y zip
      pushd scripts/visitor_count
      zip -r ../visitor_count.zip .
      gsutil cp ../visitor_count.zip gs://coffeetime-dev-cloudresume-functions
      popd
      gcloud deployment-manager deployments update cloudresume --config deployment-manager/cloudresume.yaml